services:
  - type: web
    name: newsportal-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install && cd ../news && npm install && npm run build && cd ../Backend
    startCommand: npm start
    envVars:
      - key: MONGOURI
        scope: service
        value: mongodb+srv://${DB_USER}:${DB_PASSWORD}@${DB_CLUSTER}/?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
