services:
  - type: web
    name: newsportal-backend
    runtime: node
    buildCommand: npm run install:all && npm run build:frontend
    startCommand: cd Backend && npm start
    envVars:
      - key: MONGOURI
        scope: service
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
